-- ============================================================
-- 182_ai_programmer_proposals.sql
--
-- Phase 2E — Programmer Agent proposal system.
--
-- Stores structured proposals generated by the Programmer Agent
-- for trainer review and approval. The LLM creates DRAFT proposals;
-- only the trainer's explicit confirmation leads to execution.
--
-- LIFECYCLE:
--   draft → approved → executed
--   draft → rejected
--   draft → expired (TTL sweep)
--
-- SAFETY:
--   - Every row is organization_id + client_id scoped
--   - requires_trainer_approval is ALWAYS true
--   - Execution uses existing deterministic write paths
--   - The model never directly modifies workout plans
-- ============================================================

CREATE TABLE IF NOT EXISTS ai_programmer_proposals (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  client_id       UUID NOT NULL REFERENCES pt_clients(id) ON DELETE CASCADE,

  -- Proposal content
  proposal_type   TEXT NOT NULL CHECK (proposal_type IN (
                    'progress_load', 'regress_load', 'change_rep_range',
                    'adjust_sets', 'exercise_substitution', 'volume_adjustment',
                    'intensity_adjustment', 'deload_proposal',
                    'recovery_modification', 'explain_progression'
                  )),
  summary         TEXT NOT NULL,
  reason          TEXT NOT NULL,

  -- Evidence and context
  evidence                JSONB NOT NULL DEFAULT '[]',
  current_state           JSONB NOT NULL DEFAULT '{}',
  deterministic_recommendation JSONB,
  ai_recommendation       JSONB,

  -- Confidence and safety
  confidence      REAL NOT NULL DEFAULT 0.5 CHECK (confidence >= 0.0 AND confidence <= 1.0),
  safety_flags    JSONB NOT NULL DEFAULT '[]',

  -- Lifecycle
  status          TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
                    'draft', 'approved', 'rejected', 'expired', 'executed', 'deleted'
                  )),
  requires_trainer_approval BOOLEAN NOT NULL DEFAULT true,

  -- Review
  reviewed_by     TEXT,
  reviewed_at     TIMESTAMPTZ,
  rejection_reason TEXT,

  -- Execution
  executed_at     TIMESTAMPTZ,

  -- Audit
  created_by      TEXT,
  expires_at      TIMESTAMPTZ NOT NULL,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup: pending proposals for a client
CREATE INDEX IF NOT EXISTS idx_ai_programmer_proposals_lookup
  ON ai_programmer_proposals (client_id, organization_id, status)
  WHERE status = 'draft';

-- Expiration sweep
CREATE INDEX IF NOT EXISTS idx_ai_programmer_proposals_expiring
  ON ai_programmer_proposals (expires_at)
  WHERE status = 'draft' AND expires_at IS NOT NULL;

COMMENT ON TABLE  public.ai_programmer_proposals IS
  'Phase 2E — Programmer Agent proposals. AI generates DRAFT proposals; trainers approve/reject. The model never directly modifies workout plans.';
COMMENT ON COLUMN public.ai_programmer_proposals.proposal_type IS
  'Type of programming change proposed: progress_load, regress_load, change_rep_range, adjust_sets, exercise_substitution, volume_adjustment, intensity_adjustment, deload_proposal, recovery_modification, explain_progression.';
COMMENT ON COLUMN public.ai_programmer_proposals.evidence IS
  'JSONB array of evidence items supporting the proposal. Each item has type, description, source, and value.';
COMMENT ON COLUMN public.ai_programmer_proposals.requires_trainer_approval IS
  'Always true. The model never directly modifies workout plans. Trainer approval is mandatory.';
